services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234o1234
      - POSTGRES_DB=qrent_db
    ports:
      - '5432:5432'
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local