rootProject.name = "qrental"

pluginManagement {
    repositories.gradlePluginPortal()
}

dependencyResolutionManagement {
    repositories.mavenCentral()
}

include("source:app")
include("source:ui-thymeleaf")

include("source:cross:task")

include("source:cross:email:api:in")
include("source:cross:email:core")
include("source:cross:email:config")

include("source:cross:security:api:in")
include("source:cross:security:core")
include("source:cross:security:config")

include("source:domain:common:api")
include("source:domain:common:core")
include("source:domain:common:utils")
include("source:domain:common:config")

include("source:domain:driver:api:in")
include("source:domain:driver:api:out")
include("source:domain:driver:domain")
include("source:domain:driver:core")
include("source:domain:driver:persistence:adapter")
include("source:domain:driver:persistence:entity")
include("source:domain:driver:persistence:repository")
include("source:domain:driver:persistence:flyway")
include("source:domain:driver:config")

include("source:domain:car:api:in")
include("source:domain:car:api:out")
include("source:domain:car:domain")
include("source:domain:car:core")
include("source:domain:car:persistence:adapter")
include("source:domain:car:persistence:entity")
include("source:domain:car:persistence:repository")
include("source:domain:car:persistence:flyway")
include("source:domain:car:config")

include("source:domain:firm:api:in")
include("source:domain:firm:api:out")
include("source:domain:firm:domain")
include("source:domain:firm:core")
include("source:domain:firm:persistence:adapter")
include("source:domain:firm:persistence:entity")
include("source:domain:firm:persistence:repository")
include("source:domain:firm:persistence:flyway")
include("source:domain:firm:config")

include("source:domain:bonus:api:in")
include("source:domain:bonus:api:out")
include("source:domain:bonus:domain")
include("source:domain:bonus:core")
include("source:domain:bonus:persistence:adapter")
include("source:domain:bonus:persistence:entity")
include("source:domain:bonus:persistence:repository")
include("source:domain:bonus:persistence:flyway")
include("source:domain:bonus:config")

include("source:domain:constant:api:in")
include("source:domain:constant:api:out")
include("source:domain:constant:domain")
include("source:domain:constant:core")
include("source:domain:constant:persistence:adapter")
include("source:domain:constant:persistence:entity")
include("source:domain:constant:persistence:repository")
include("source:domain:constant:persistence:flyway")
include("source:domain:constant:config")

include("source:domain:invoice:api:in")
include("source:domain:invoice:api:out")
include("source:domain:invoice:domain")
include("source:domain:invoice:core")
include("source:domain:invoice:persistence:adapter")
include("source:domain:invoice:persistence:entity")
include("source:domain:invoice:persistence:repository")
include("source:domain:invoice:persistence:flyway")
include("source:domain:invoice:config")

include("source:domain:insurance:api:in")
include("source:domain:insurance:api:out")
include("source:domain:insurance:domain")
include("source:domain:insurance:core")
include("source:domain:insurance:persistence:adapter")
include("source:domain:insurance:persistence:entity")
include("source:domain:insurance:persistence:repository")
include("source:domain:insurance:persistence:flyway")
include("source:domain:insurance:config")

include("source:domain:contract:api:in")
include("source:domain:contract:api:out")
include("source:domain:contract:domain")
include("source:domain:contract:core")
include("source:domain:contract:persistence:adapter")
include("source:domain:contract:persistence:entity")
include("source:domain:contract:persistence:repository")
include("source:domain:contract:persistence:flyway")
include("source:domain:contract:config")

include("source:domain:transaction:api:in")
include("source:domain:transaction:api:out")
include("source:domain:transaction:domain")
include("source:domain:transaction:core")
include("source:domain:transaction:persistence:adapter")
include("source:domain:transaction:persistence:entity")
include("source:domain:transaction:persistence:repository")
include("source:domain:transaction:persistence:flyway")
include("source:domain:transaction:config")

include("source:domain:bonus:api:in")
include("source:domain:bonus:api:out")
include("source:domain:bonus:domain")
include("source:domain:bonus:core")
include("source:domain:bonus:persistence:adapter")
include("source:domain:bonus:persistence:entity")
include("source:domain:bonus:persistence:repository")
include("source:domain:bonus:persistence:flyway")
include("source:domain:bonus:config")



include("source:domain:user:api:in")
include("source:domain:user:api:out")
include("source:domain:user:domain")
include("source:domain:user:core")
include("source:domain:user:persistence:adapter")
include("source:domain:user:persistence:entity")
include("source:domain:user:persistence:repository")
include("source:domain:user:persistence:flyway")
include("source:domain:user:config")

