[libraries]
q-lombok = "org.projectlombok:lombok:1.18.26"
q-jakarta-persistence = "jakarta.persistence:jakarta.persistence-api:3.1.0"
q-jakarta-transaction = "jakarta.transaction:jakarta.transaction-api:2.0.1"
q-librepdf-openpdf = "com.github.librepdf:openpdf:1.3.30"