[libraries]
q-lombok = "org.projectlombok:lombok:1.18.30"
q-jakarta-persistence = "jakarta.persistence:jakarta.persistence-api:3.1.0"
q-jakarta-transaction = "jakarta.transaction:jakarta.transaction-api:2.0.1"
q-hibernate-envers = "org.hibernate.orm:hibernate-envers:6.6.2.Final"
q-hypersistence-utils-hibernate = "io.hypersistence:hypersistence-utils-hibernate-60:3.9.4"
q-librepdf-openpdf = "com.github.librepdf:openpdf:1.3.30"