server:
  port: ${PORT:8181}
spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://ec2-18-202-8-133.eu-west-1.compute.amazonaws.com:5432/d9p4dpgt8k95od}
  jpa:
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  mail:
    username: billing@qrent.ee
    password: wzqwqrciagzpxcbv
    host: smtp.zone.eu
    port: 587
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

management:
  endpoints:
    web:
      exposure:
        include: health, info