server:
  port: 8181
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  mail:
    username: billing@qrent.ee
    password: shzlahiyqdwcbzqk
    host: smtp.zone.eu
    port: 587
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true