server:
  port: 8182

spring:
  datasource:
    hikari:
      schema: billing
  jpa:
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    #hibernate:
    #ddl-auto: update
  mail:
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  flyway:
    locations: classpath:db/migration/notification
    table: flyway_schema_history_notification
management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    git:
      mode: full